# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugdetail',
            name='bug_type',
            field=models.CharField(choices=[('UI', 'User Interface'), ('functional', 'Functional'), ('recurring', 'Recurring')], default='functional', max_length=15),
        ),
    ]
